site_name: Front-end Web Design (WIT 2019)
theme:
  name: 'material'
  custom_dir: 'theme'
  
extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
